export { default as Home }  from "./Home"
export { default as About }  from "./About"
export { default as Resume }  from "./Resume"
export { default as Skills }  from "./Skills"
export { default as Projects }  from "./Projects"
export { default as Page404 }  from "./Page404"
export { default as Contact }  from "./Contact"